Remove six and pyyaml as dependency
Remove six and pyyaml as dependency, because they are already installed
by salt.

Fixes the following error message during install of salt-lint:

    ERROR: salt 2019.2.1 has requirement PyYAML<5.1, but you'll have pyyaml 5.1.2 which is incompatible.

Signed-off-by: Roald Nefs <info@roaldnefs.com>